import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nou Design Studio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1>Nou Studio</h1>
        <nav>
          <ul>
            <li>
              <Link href='/services'>
                <a>services</a>
              </Link>
            </li>
            <li>
              <Link href='/work'>
                <a>work</a>

              </Link>
            </li>
            <li>
              <Link href='/contact'>
                <a>contact</a>

              </Link>
            </li>
          </ul>
        </nav>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
