import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Nav from '../components/Nav'




export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nou Design Studio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header className={styles.header}>
        <Nav />
      </header>
      <main className={styles.main}>
        <div className={styles.hero}>
        <Image src='/trial.svg' alt='nou logo'  width={200} height={200} />

        </div>            

        <section>
         <h3>Coming Soon..</h3>

        </section>
         <a href='https://www.instagram.com/noudesign.studio/' target="_blank" className={styles.social}>
            <Image 
            src='/icons8-instagram-50.png' 
            alt='instagram link' 
            width={40} height={40} 
            className={styles.social}
            />
          </a>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
