import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Nav from '../components/Nav'




export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nou Design Studio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header>
      </header>
      <main className={styles.main}>
        <div className={styles.hero}>
        <Image src='/trial.svg' alt='nou logo'  width={200} height={200} preserveAspectRatio="none"/>

        </div>
        <Nav />
          <a href='https://www.instagram.com/noudesign.studio/' target="_blank" className={styles.social}>
            <Image 
            src='/../public/icons8-instagram-50.png' 
            alt='instagram link' 
            width={50} height={50} 
            className={styles.social}/>
          </a>



        {/* <nav>
          <ul>
            <li>
              <Link href='/services'>
                <a>services</a>
              </Link>
            </li>
            <li>
              <Link href='/work'>
                <a>work</a>

              </Link>
            </li>
            <li>
              <Link href='/contact'>
                <a>contact</a>

              </Link>
            </li>
          </ul>
        </nav> */}
        <section>
          <p>Example text about us</p>
        </section>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
